from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.account_login_choice, name='account_login_choice'),
    path('register/', views.account_register_choice, name='account_register_choice'),
    path('traveler/login/', views.traveler_login, name='traveler_login'),
    path('traveler/register/', views.traveler_register, name='traveler_register'),  
    path('traveler/home/', views.traveler_home, name='traveler_home'),
    path('traveler/wishlist/', views.traveler_wishlist, name='traveler_wishlist'),
    path('traveler/achievements/', views.traveler_achievements, name='traveler_achievements'),
    path('traveler/bookings/', views.traveler_bookings, name='traveler_bookings'),
    path('traveler/transactions/', views.traveler_transactions, name='traveler_transactions'),
    path('traveler/profile/', views.traveler_profile, name='traveler_profile'),
    path('wishlist/toggle/', views.wishlist_toggle, name='wishlist_toggle'),

    path('vendors/<int:vendor_id>/', views.vendor_public_profile, name='vendor_public_profile'),

    path('vendor/login/', views.vendor_login, name='vendor_login'),
    path('vendor/register/', views.vendor_register, name='vendor_register'),
    path('vendor/packages/new/', views.vendor_package_create, name='vendor_package_create'),
    path('vendor/packages/<int:package_id>/edit/', views.vendor_package_edit, name='vendor_package_edit'),
    path('vendor/packages/<int:package_id>/delete/', views.vendor_package_delete, name='vendor_package_delete'),
    path('vendor/dashboard/', views.vendor_dashboard, name='vendor_dashboard'),
    path('vendor/profile/', views.vendor_profile, name='vendor_profile'),
    path('vendor/packages/', views.vendor_packages, name='vendor_packages'),
    path('vendor/packages/<int:package_id>/feature/', views.vendor_feature_toggle, name='vendor_feature_toggle'),
    path('vendor/bookings/', views.vendor_bookings, name='vendor_bookings'),
    path('vendor/transactions/', views.vendor_transactions, name='vendor_transactions'),
    path('vendor/bookings/<int:booking_id>/status/', views.vendor_booking_status_update, name='vendor_booking_status_update'),
    path('vendor/reviews/', views.vendor_reviews, name='vendor_reviews'),
    path('vendor/analytics/', views.vendor_analytics, name='vendor_analytics'),
    path('vendor/settings/', views.vendor_settings, name='vendor_settings'),
    path('vendor/subscriptions/<int:plan_id>/purchase/', views.vendor_subscription_purchase, name='vendor_subscription_purchase'),
    path('vendor/subscriptions/esewa/success/', views.vendor_subscription_esewa_success, name='vendor_subscription_esewa_success'),
    path('vendor/subscriptions/esewa/failure/', views.vendor_subscription_esewa_failure, name='vendor_subscription_esewa_failure'),
    path('vendor/subscriptions/stripe/success/', views.vendor_subscription_stripe_success, name='vendor_subscription_stripe_success'),
    path('vendor/subscriptions/stripe/cancel/', views.vendor_subscription_stripe_cancel, name='vendor_subscription_stripe_cancel'),
    path('vendor/feature-slots/<int:slot_id>/purchase/', views.vendor_feature_slot_purchase, name='vendor_feature_slot_purchase'),
    path('vendor/feature-slots/esewa/success/', views.vendor_feature_slot_esewa_success, name='vendor_feature_slot_esewa_success'),
    path('vendor/feature-slots/esewa/failure/', views.vendor_feature_slot_esewa_failure, name='vendor_feature_slot_esewa_failure'),
    path('vendor/feature-slots/stripe/success/', views.vendor_feature_slot_stripe_success, name='vendor_feature_slot_stripe_success'),
    path('vendor/feature-slots/stripe/cancel/', views.vendor_feature_slot_stripe_cancel, name='vendor_feature_slot_stripe_cancel'),

    path('support/chat/', views.support_chat, name='support_chat'),
    path('support/widget/', views.support_widget_data, name='support_widget_data'),
    path('support/widget/send/', views.support_widget_send, name='support_widget_send'),
    path('notifications/', views.notifications_list, name='notifications_list'),
    path('notifications/data/', views.notifications_data, name='notifications_data'),
    path('notifications/read/', views.notifications_mark_read, name='notifications_mark_read'),
    
    path('admin/login/', views.admin_login, name='admin_login'),
    path('admin/support/', views.admin_support_inbox, name='admin_support_inbox'),
    path('admin/support/<int:conversation_id>/', views.admin_support_chat, name='admin_support_chat'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/analytics/', views.admin_analytics_api, name='admin_analytics_api'),
    path('admin/transactions/', views.admin_transactions, name='admin_transactions'),
    path('admin/profile/', views.admin_profile, name='admin_profile'),
    path('admin/vendors/<int:vendor_id>/', views.admin_vendor_detail, name='admin_vendor_detail'),
    path('admin/vendors/<int:vendor_id>/action/', views.admin_vendor_action, name='admin_vendor_action'),
    path('admin/packages/<int:package_id>/toggle/', views.admin_package_toggle, name='admin_package_toggle'),
    path('admin/packages/<int:package_id>/feature/', views.admin_feature_toggle, name='admin_feature_toggle'),
    path('admin/subscriptions/plans/new/', views.admin_subscription_plan_create, name='admin_subscription_plan_create'),
    path('admin/feature-slots/new/', views.admin_feature_slot_create, name='admin_feature_slot_create'),

    path('verify-otp/', views.verify_otp_view, name='verify_otp'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),
    
    path('logout/', views.logout_view, name='logout'),
]
