# Generated by Django 4.2 on 2026-02-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='inclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('expedition', 'Expedition')], max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='group_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='best_season',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
