# Generated by Django 4.2 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_packageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
