# Generated by Django 4.2 on 2026-02-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_packageimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageimage',
            options={'ordering': ('order', 'created_at', 'id')},
        ),
    ]
