# Generated by Django 5.2.9 on 2026-03-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment_parent_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('TREK', 'Trek'), ('TOUR', 'Tour')], default='TREK', max_length=10),
        ),
    ]
