# Generated by ChatGPT on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_supportconversation_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
