# Generated by ChatGPT on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_package_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='has_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_accommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_permits',
            field=models.BooleanField(default=False),
        ),
    ]
