# Generated by Django 4.2.29 on 2026-03-27 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_vendorprofile_document'),
        ('core', '0021_transaction_transaction_unique_transaction_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_transaction_booking',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('subscription', 'Subscription')], default='booking', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.vendorsubscription'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.booking'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking',), name='unique_transaction_booking'),
        ),
    ]
