# Generated by Django 4.2.29 on 2026-03-29 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_booking_discount_amount_booking_original_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='related_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='core.booking'),
        ),
    ]
