# Generated by Django 4.2.29 on 2026-03-29 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_featureslot_vendorfeature'),
        ('core', '0026_specialoffer_traveltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vendor_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.vendorfeature'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('subscription', 'Subscription'), ('feature_slot', 'Feature Slot')], default='booking', max_length=20),
        ),
    ]
