# Generated by Django 4.2.29 on 2026-04-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_featuredpackage_featureplan_and_more'),
        ('core', '0028_sitesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='featured_slots',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='vendor_feature',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='vendor_subscription',
        ),
        migrations.AddField(
            model_name='transaction',
            name='feature_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.vendorfeaturesubscription'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('feature_subscription', 'Feature Subscription')], default='booking', max_length=20),
        ),
    ]
