# Generated by Django 4.2 on 2026-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='routing_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='vendor_covers/'),
        ),
    ]
