# Generated by Django 5.2.9 on 2026-03-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_vendorsubscription_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('booking', 'Booking'), ('community_post', 'Community Post'), ('like', 'Like'), ('comment', 'Comment'), ('vendor_approval', 'Vendor Approval'), ('admin_message', 'Admin Message'), ('package_approved', 'Package Approved'), ('support_message', 'Support Message'), ('package_submission', 'Package Submission'), ('user_registration', 'User Registration')], max_length=40)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
