# Generated by Django 4.2 on 2026-03-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_seed_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
