# Generated by Django 4.2.29 on 2026-03-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_vendorprofile_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_promotions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking', 'Booking'), ('community_post', 'Community Post'), ('like', 'Like'), ('comment', 'Comment'), ('vendor_approval', 'Vendor Approval'), ('admin_message', 'Admin Message'), ('package_approved', 'Package Approved'), ('support_message', 'Support Message'), ('package_submission', 'Package Submission'), ('user_registration', 'User Registration'), ('promotion', 'Promotion')], max_length=40),
        ),
    ]
