# Generated by Django 4.2.29 on 2026-04-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_featureslot_vendorfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-featured_date',),
            },
        ),
        migrations.CreateModel(
            name='FeaturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slots_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('price', 'slots_count', 'name'),
            },
        ),
        migrations.CreateModel(
            name='VendorFeatureSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('slots_total', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('esewa', 'eSewa'), ('stripe', 'Stripe')], default='esewa', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.RemoveField(
            model_name='vendorfeature',
            name='package',
        ),
        migrations.RemoveField(
            model_name='vendorfeature',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='vendorfeature',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorsubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='vendorsubscription',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='FeatureSlot',
        ),
    ]
