# Generated by Django 4.2.29 on 2026-04-03 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_featuredpackage_featureplan_and_more'),
        ('core', '0029_remove_package_is_featured_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorFeature',
        ),
        migrations.DeleteModel(
            name='VendorSubscription',
        ),
        migrations.DeleteModel(
            name='VendorSubscriptionPlan',
        ),
        migrations.AddField(
            model_name='vendorfeaturesubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='accounts.featureplan'),
        ),
        migrations.AddField(
            model_name='vendorfeaturesubscription',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuredpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='core.package'),
        ),
        migrations.AddField(
            model_name='featuredpackage',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_packages', to='accounts.vendorfeaturesubscription'),
        ),
        migrations.AddConstraint(
            model_name='featuredpackage',
            constraint=models.UniqueConstraint(fields=('subscription', 'package'), name='unique_featured_package_per_subscription'),
        ),
    ]
