# core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home_page'),
    path('community/', views.community_feed, name='community_feed'),
    path('dashboard/community/', views.community_dashboard, name='community_dashboard'),
    path('community/posts/new/', views.community_post_create, name='community_post_create'),
    path('community/posts/<int:post_id>/edit/', views.community_post_edit, name='community_post_edit'),
    path('community/posts/<int:post_id>/delete/', views.community_post_delete, name='community_post_delete'),
    path('community/posts/<int:post_id>/like/', views.community_post_like_toggle, name='community_post_like_toggle'),
    path('community/posts/<int:post_id>/comment/', views.community_comment_create, name='community_comment_create'),
    path('packages/', views.package_list, name='package_list'),
    path('packages/treks/', views.trek_package_list, name='package_treks'),
    path('packages/tours/', views.tour_package_list, name='package_tours'),
    path('explore-map/', views.explore_map, name='explore_map'),
    path('api/destinations/', views.destinations_api, name='destinations_api'),
    path('api/packages/map/', views.packages_map_api, name='packages_map_api'),
    path('api/packages/search/', views.packages_search_api, name='packages_search_api'),
    path('packages/<int:package_id>/book/', views.package_book, name='package_book'),
    path('packages/<int:package_id>/', views.package_detail, name='package_detail'),
    path('bookings/<int:booking_id>/confirmation/', views.booking_confirmation, name='booking_confirmation'),
    path('bookings/<int:booking_id>/cancel/', views.booking_checkout_cancel, name='booking_checkout_cancel'),
    path('bookings/<int:booking_id>/stripe/checkout/', views.booking_stripe_checkout, name='booking_stripe_checkout'),
    path('bookings/<int:booking_id>/esewa/checkout/', views.booking_esewa_checkout, name='booking_esewa_checkout'),
    path('bookings/<int:booking_id>/esewa/success/', views.booking_esewa_success, name='booking_esewa_success'),
    path('bookings/<int:booking_id>/esewa/failure/', views.booking_esewa_failure, name='booking_esewa_failure'),
    path('invoice/<int:booking_id>/', views.booking_invoice, name='booking_invoice'),
    path('invoice/<int:booking_id>/download/', views.booking_invoice_download, name='booking_invoice_download'),
    path('reviews/', views.review_list, name='review_list'),
    path('reviews/submit/', views.submit_review, name='submit_review'),
    path('about/', views.about, name='about'),
    path('blog/', views.blog_list, name='blog_list'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('contact/', views.contact, name='contact'),
]
