# core/urls.py
from django.urls import path
from .views.booking_views import (
    booking_confirmation,
    booking_detail,
    booking_invoice,
    booking_invoice_download,
    package_book,
)
from .views.community_views import (
    community_comment_create,
    community_dashboard,
    community_feed,
    community_post_create,
    community_post_delete,
    community_post_edit,
    community_post_like_toggle,
    community_post_tag_vendor,
)
from .views.package_views import (
    about,
    blog_detail,
    blog_list,
    contact,
    destinations_api,
    explore_map,
    home,
    package_detail,
    package_details_api,
    package_list,
    packages_map_api,
    packages_search_api,
    public_traveler_profile,
    tour_package_list,
    trek_package_list,
)
from .views.payment_views import (
    booking_esewa_checkout,
    booking_esewa_failure,
    booking_esewa_success,
    booking_stripe_checkout,
)
from .views.review_views import review_list, submit_review

urlpatterns = [
    path('', home, name='home'),
    path('home/', home, name='home_page'),
    path('profile/<int:user_id>/', public_traveler_profile, name='public_traveler_profile'),
    path('profile/<int:user_id>/', public_traveler_profile, name='view_profile'),
    path('community/', community_feed, name='community_feed'),
    path('dashboard/community/', community_dashboard, name='community_dashboard'),
    path('community/posts/new/', community_post_create, name='community_post_create'),
    path('community/posts/<int:post_id>/edit/', community_post_edit, name='community_post_edit'),
    path('community/posts/<int:post_id>/edit/', community_post_edit, name='edit_post'),
    path('community/posts/<int:post_id>/tag-vendor/', community_post_tag_vendor, name='tag_vendor'),
    path('community/posts/<int:post_id>/delete/', community_post_delete, name='community_post_delete'),
    path('community/posts/<int:post_id>/delete/', community_post_delete, name='delete_post'),
    path('community/posts/<int:post_id>/like/', community_post_like_toggle, name='community_post_like_toggle'),
    path('community/posts/<int:post_id>/comment/', community_comment_create, name='community_comment_create'),
    path('packages/', package_list, name='package_list'),
    path('packages/', package_list, name='packages'),
    path('packages/treks/', trek_package_list, name='package_treks'),
    path('packages/tours/', tour_package_list, name='package_tours'),
    path('explore-map/', explore_map, name='explore_map'),
    path('package/<int:package_id>/details/', package_details_api, name='package_details_api'),
    path('api/destinations/', destinations_api, name='destinations_api'),
    path('api/packages/map/', packages_map_api, name='packages_map_api'),
    path('api/packages/search/', packages_search_api, name='packages_search_api'),
    path('packages/<int:package_id>/book/', package_book, name='package_book'),
    path('packages/<int:package_id>/', package_detail, name='package_detail'),
    path('bookings/<int:booking_id>/confirmation/', booking_confirmation, name='booking_confirmation'),
    path('bookings/<int:booking_id>/detail/', booking_detail, name='booking_detail'),
    path('bookings/<int:booking_id>/stripe/checkout/', booking_stripe_checkout, name='booking_stripe_checkout'),
    path('bookings/<int:booking_id>/esewa/checkout/', booking_esewa_checkout, name='booking_esewa_checkout'),
    path('bookings/<int:booking_id>/esewa/success/', booking_esewa_success, name='booking_esewa_success'),
    path('bookings/<int:booking_id>/esewa/failure/', booking_esewa_failure, name='booking_esewa_failure'),
    path('invoice/<int:booking_id>/', booking_invoice, name='booking_invoice'),
    path('invoice/<int:booking_id>/download/', booking_invoice_download, name='booking_invoice_download'),
    path('reviews/', review_list, name='review_list'),
    path('reviews/submit/', submit_review, name='submit_review'),
    path('about/', about, name='about'),
    path('blog/', blog_list, name='blog_list'),
    path('blog/<slug:slug>/', blog_detail, name='blog_detail'),
    path('contact/', contact, name='contact'),
]
